import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { Background, Controls, Handle, Position, ReactFlow, type Node, type NodeProps, type ReactFlowInstance } from '@xyflow/react'
import { ArrowLeft, Bot, ChevronRight, CornerUpLeft, Download, FilePlus, Focus, History, Info, LoaderCircle, Menu, Plus, Save, Send, Sparkles, Undo2, X } from 'lucide-react'

type TreeNode = { id: string; parent: string | null; type: string; depth: number; status: string; title: string; detail?: string; time_label?: string; children: string[]; file: string }
type Manifest = { session_id: string; root: { node_id: string; time_anchor: string; age_anchor?: number | null }; nodes: TreeNode[]; reverse_history: unknown[] }
type LifeData = { item: TreeNode; anchor: string; onInspect: (id: string) => void; onKeyboardFocus: (id: string) => void; onContinue: (id: string) => void; onRestore: (id: string) => void; onGenerate: (id: string, one?: boolean) => void; onManual: (id: string, title: string) => void; onRespond: (id: string, text: string) => void; onGenerateResponse: (id: string) => void; onGenerateSituation: (id: string) => void; onManualSituation: (id: string, title: string) => void; onOutcome: (id: string) => void; onReverse: (id: string) => void }
type LifeNode = Node<LifeData, 'life'>
type SessionSummary = { session_id: string; created_at: string; title: string; node_count: number; pending_count: number }
type NodeDetail = { id: string; type: string; title: string; status: string; content: Record<string, string> }
type Draft = { parentId: string; type: 'branch' | 'difficulty' | 'response' | 'situation'; relation: 'child' | 'sibling'; anchorId: string }
const templates = ['我现在 20 岁，要不要辍学创业？', '考研还是直接工作？', '要不要去北京发展？', '高考志愿应该怎么选？']

async function request(path: string, method = 'GET', data?: unknown) { const res = await fetch(`/api${path}`, { method, headers: data ? { 'Content-Type': 'application/json' } : undefined, body: data ? JSON.stringify(data) : undefined }); if (!res.ok) throw new Error((await res.json()).error || '请求失败'); return res.json() }
function monthLabel(node: TreeNode, anchor: string) { return node.time_label || (node.type === 'decision' ? anchor : '') }

function SimulatorNode({ data }: NodeProps<LifeNode>) {
  const { item } = data; const [manual, setManual] = useState(false); const [expandSibling, setExpandSibling] = useState(false); const [manualPossible, setManualPossible] = useState(false); const [value, setValue] = useState(''); const [absolute, setAbsolute] = useState(false); const responseInput = useRef<HTMLInputElement>(null); const nodeSurface = useRef<HTMLDivElement>(null)
  useEffect(() => { if (!expandSibling) return; const closeOnOutside = (event: PointerEvent) => { if (!(event.target instanceof Element) || !nodeSurface.current?.contains(event.target)) setExpandSibling(false) }; document.addEventListener('pointerdown', closeOnOutside, true); return () => document.removeEventListener('pointerdown', closeOnOutside, true) }, [expandSibling])
  const submit = (action: () => void) => { action(); setValue(''); setManual(false) }
  return <div ref={nodeSurface} tabIndex={0} aria-label={`第 ${Number(item.id.slice(1))} 步，${item.title}`} className={`life-node ${item.type} ${item.status}`} onFocus={() => data.onKeyboardFocus(item.id)} onMouseDownCapture={() => data.onInspect(item.id)} onPointerDown={() => data.onInspect(item.id)} onClick={() => data.onInspect(item.id)}>
    <Handle type="target" position={Position.Left} />
    <div className="node-top"><span className="node-kind"><i className="node-order">{Number(item.id.slice(1))}</i>{item.type}</span><span className="node-top-actions">{item.time_label && <button className="time" onClick={(event) => { event.stopPropagation(); setAbsolute(!absolute) }}>{absolute ? item.time_label : '几个月后'}</button>}<button className="inspect-node" title="查看详情" aria-label="查看详情" onPointerDown={(event) => event.stopPropagation()} onClick={(event) => { event.stopPropagation(); data.onInspect(item.id) }}><Info size={13} /></button></span></div>
    <strong>{item.status === 'pending' ? <span className="generating"><LoaderCircle size={15} />正在推演</span> : item.status === 'error' ? '推演失败，点击重试' : item.title}</strong>
    {item.status === 'reversed' && <div className="reversed-note"><span>已放弃的路径</span><button className="nodrag nopan" onPointerDown={(event) => event.stopPropagation()} onClick={(event) => { event.stopPropagation(); data.onRestore(item.id) }}>恢复并继续探索</button><button className="nodrag nopan" onPointerDown={(event) => event.stopPropagation()} onClick={(event) => { event.stopPropagation(); data.onContinue(item.parent || item.id) }}>返回当前探索</button></div>}
    {item.type === 'response' && item.detail && <p className="response-text">{item.detail}</p>}
    {item.type === 'difficulty' && <span className="tagline">概率 / 影响将在推演中标记</span>}
    {item.type === 'difficulty' && item.status === 'active' && <div className="node-input"><input ref={responseInput} value={value} onChange={(e) => setValue(e.target.value)} placeholder="你会怎么处理？" onKeyDown={(e) => e.key === 'Enter' && value.trim() && submit(() => data.onRespond(item.id, value))} /><button onClick={() => value.trim() && submit(() => data.onRespond(item.id, value))}><Send size={14} /></button></div>}
    {item.type === 'situation' && item.status === 'active' && <button className="inline-action" onClick={() => data.onOutcome(item.id)}>查看阶段结局</button>}
    {item.type === 'branch' && item.status === 'active' && <div className="node-actions"><button title="AI 追加一个困难" onClick={() => data.onGenerate(item.id, true)}><Bot size={14} /> AI 生成</button><button title="手动添加困难" onClick={() => setManual(!manual)}><Plus size={14} /> 手动添加</button></div>}
    {manual && <div className="node-input"><input autoFocus value={value} onChange={(e) => setValue(e.target.value)} placeholder="写下一个可能的困难" onKeyDown={(e) => e.key === 'Enter' && value.trim() && submit(() => data.onManual(item.id, value))} /><button onClick={() => value.trim() && submit(() => data.onManual(item.id, value))}><Send size={14} /></button></div>}
    {item.type === 'branch' && item.children.length === 0 && item.status === 'active' && <button className="inline-action" onClick={() => data.onGenerate(item.id)}>生成可能遇到的困难</button>}
    {manualPossible && <div className="node-input"><input autoFocus value={value} onChange={(event) => setValue(event.target.value)} placeholder={item.type === 'response' ? '手动输入另一种应对策略' : '手动描述一个新的同级可能'} onKeyDown={(event) => event.key === 'Enter' && value.trim() && submit(() => item.type === 'response' ? data.onRespond(item.parent!, value) : data.onManualSituation(item.parent!, value))} /><button onClick={() => value.trim() && submit(() => item.type === 'response' ? data.onRespond(item.parent!, value) : data.onManualSituation(item.parent!, value))}><Send size={14} /></button></div>}
    {item.status === 'active' && item.type !== 'outcome' && <div className={`hover-add ${expandSibling ? 'expanded' : ''}`}><button className="hover-add-trigger nodrag nopan" onPointerDown={(event) => event.stopPropagation()} onClick={(event) => { event.stopPropagation(); setExpandSibling(!expandSibling) }}><Plus size={13} />{item.type === 'branch' ? '添加新的困难' : item.type === 'difficulty' ? '添加新的应对策略' : '添加新的可能'}</button>{expandSibling && <div className="hover-add-options">{item.type === 'branch' && <><button className="nodrag nopan" onPointerDown={(event) => event.stopPropagation()} onClick={(event) => { event.stopPropagation(); data.onGenerate(item.id, true); setExpandSibling(false) }}>AI 生成</button><button className="nodrag nopan" onPointerDown={(event) => event.stopPropagation()} onClick={(event) => { event.stopPropagation(); setManual(true); setExpandSibling(false) }}>手动输入</button></>}{item.type === 'difficulty' && <><button className="nodrag nopan" onPointerDown={(event) => event.stopPropagation()} onClick={(event) => { event.stopPropagation(); data.onGenerateResponse(item.id); setExpandSibling(false) }}>AI 生成</button><button className="nodrag nopan" onPointerDown={(event) => event.stopPropagation()} onClick={(event) => { event.stopPropagation(); responseInput.current?.focus(); setExpandSibling(false) }}>手动输入</button></>}{item.type === 'response' && <><button className="nodrag nopan" onPointerDown={(event) => event.stopPropagation()} onClick={(event) => { data.onGenerateResponse(item.parent!); setExpandSibling(false) }}>AI 生成</button><button className="nodrag nopan" onPointerDown={(event) => event.stopPropagation()} onClick={(event) => { event.stopPropagation(); setManualPossible(true); setExpandSibling(false) }}>手动输入</button></>}{item.type === 'situation' && item.parent && <><button className="nodrag nopan" onPointerDown={(event) => event.stopPropagation()} onClick={(event) => { data.onGenerateSituation(item.parent!); setExpandSibling(false) }}>AI 生成</button><button className="nodrag nopan" onPointerDown={(event) => event.stopPropagation()} onClick={(event) => { event.stopPropagation(); setManualPossible(true); setExpandSibling(false) }}>手动输入</button></>}</div>}</div>}
    {item.type !== 'decision' && item.status === 'active' && <button className="reverse" title="Reverse" onClick={() => data.onReverse(item.id)}><CornerUpLeft size={14} /> reverse</button>}
    <Handle type="source" position={Position.Right} />
  </div>
}

function DraftNode({ data }: { data: { type: Draft['type']; onSubmit: (title: string) => void; onCancel: () => void } }) {
  const [value, setValue] = useState(''); const input = useRef<HTMLInputElement>(null)
  useEffect(() => { input.current?.focus() }, [])
  const labels = { branch: '输入新的选择', difficulty: '输入新的困难', response: '输入另一种应对策略', situation: '输入新的可能' }
  return <div className="draft-node"><span>{labels[data.type]}</span><div><input ref={input} value={value} onChange={(event) => setValue(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && value.trim()) data.onSubmit(value); if (event.key === 'Escape') data.onCancel() }} placeholder="输入后按 Enter 确认" /><button onClick={() => value.trim() && data.onSubmit(value)}><Send size={14} /></button></div></div>
}

function DetailPanel({ detail, onEnter, onClose }: { detail: NodeDetail | null; onEnter: () => void; onClose: () => void }) {
  if (!detail) return null
  const labels: Record<string, string> = { description: '事件描述', cause: '因果链', frequency: '发生概率', impact: '影响程度', text: '我的应对', summary: '路径说明', trend: '局面走向', time_label: '时间' }
  return <aside className="detail-panel"><div className="detail-top"><span>{detail.type}</span><button onClick={onClose} title="关闭详情"><X size={17} /></button></div><div className="detail-step">第 {Number(detail.id.slice(1))} 步</div><h2>{detail.title}</h2><div className="detail-content">{Object.entries(detail.content || {}).filter(([, value]) => value).map(([key, value]) => <div key={key}><small>{labels[key] || key}</small><p>{value}</p></div>)}{Object.keys(detail.content || {}).length === 0 && <p className="detail-loading">正在读取这个节点的详细信息…</p>}</div><button className="enter-step" onClick={onEnter}><Focus size={16} />进入这一步</button></aside>
}

function CanvasMenu({ manifest, onNew, onReturn }: { manifest: Manifest | null; onNew: () => void; onReturn: () => void }) {
  const [open, setOpen] = useState(false)
  const download = () => { if (!manifest) return; const url = URL.createObjectURL(new Blob([JSON.stringify(manifest, null, 2)], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = `${manifest.session_id}-manifest.json`; link.click(); URL.revokeObjectURL(url) }
  return <div className={`canvas-menu ${open ? 'open' : ''}`}><button className="canvas-return" title="返回新建推演" onClick={onReturn}><ArrowLeft size={19} /></button><button className="menu-toggle" title="会话菜单" onClick={() => setOpen(!open)}><Menu size={19} /></button>{open && <div className="menu-popover"><button onClick={onNew}><FilePlus size={15} />新建推演</button><button onClick={() => setOpen(false)}><Save size={15} />已自动保存</button><button onClick={download}><Download size={15} />下载记忆</button></div>}</div>
}

export default function App() {
  const [question, setQuestion] = useState(''); const [manifest, setManifest] = useState<Manifest | null>(null); const [history, setHistory] = useState<SessionSummary[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const [focusedId, setFocusedId] = useState<string | null>(null); const [keyboardNodeId, setKeyboardNodeId] = useState<string | null>(null); const [selectedDetail, setSelectedDetail] = useState<NodeDetail | null>(null); const [draft, setDraft] = useState<Draft | null>(null); const [positions, setPositions] = useState<Record<string, { x: number; y: number }>>({}); const [flow, setFlow] = useState<ReactFlowInstance | null>(null)
  const loadHistory = useCallback(async () => { try { setHistory(await request('/sessions')) } catch { setHistory([]) } }, [])
  const updateSessionUrl = (id: string | null, replace = true) => { const url = new URL(window.location.href); if (id) url.searchParams.set('session', id); else url.searchParams.delete('session'); window.history[replace ? 'replaceState' : 'pushState']({}, '', url) }
  const refresh = useCallback(async (id: string) => { try { setManifest(await request(`/sessions/${id}`)); updateSessionUrl(id); void loadHistory() } catch (e) { setError(e instanceof Error ? e.message : '无法读取会话') } }, [loadHistory])
  useEffect(() => { void (async () => { const sessions = await request('/sessions') as SessionSummary[]; setHistory(sessions); const target = new URLSearchParams(window.location.search).get('session'); if (target) await refresh(target) })() }, [refresh])
  useEffect(() => { const onPopState = () => { const target = new URLSearchParams(window.location.search).get('session'); if (target) void refresh(target); else { setManifest(null); setFocusedId(null); setSelectedDetail(null) } }; window.addEventListener('popstate', onPopState); return () => window.removeEventListener('popstate', onPopState) }, [refresh])
  useEffect(() => { if (!manifest) return; const pending = manifest.nodes.some((node) => node.status === 'pending'); if (!pending) return; const timer = window.setInterval(() => refresh(manifest.session_id), 1000); return () => window.clearInterval(timer) }, [manifest, refresh])
  const create = async (value = question) => { if (!value.trim()) return; setLoading(true); setError(''); try { const next = await request('/sessions', 'POST', { question: value }); setManifest(next); updateSessionUrl(next.session_id, false); void loadHistory(); setQuestion('') } catch (e) { setError(e instanceof Error ? e.message : '创建失败') } finally { setLoading(false) } }
  const mutate = async (path: string, data?: unknown) => { if (!manifest) return; try { await request(path, 'POST', data); await refresh(manifest.session_id) } catch (e) { setError(e instanceof Error ? e.message : '操作失败') } }
  const submitDraft = async (title: string) => { if (!manifest || !draft) return; const routes = { branch: `/sessions/${manifest.session_id}/decisions/${draft.parentId}/manual-branch`, difficulty: `/sessions/${manifest.session_id}/branches/${draft.parentId}/manual-difficulty`, response: `/sessions/${manifest.session_id}/difficulties/${draft.parentId}/response`, situation: `/sessions/${manifest.session_id}/responses/${draft.parentId}/manual-situation` }; setDraft(null); await mutate(routes[draft.type], { title, text: title }) }
  const selectNode = async (nodeId: string) => { if (!manifest) return; setKeyboardNodeId(nodeId); const summary = manifest.nodes.find((node) => node.id === nodeId); if (summary) setSelectedDetail({ id: summary.id, type: summary.type, title: summary.title, status: summary.status, content: {} }); try { setSelectedDetail(await request(`/sessions/${manifest.session_id}/nodes/${nodeId}`)) } catch (e) { setError(e instanceof Error ? e.message : '无法读取节点详情') } }
  const nodes = useMemo(() => {
    if (!manifest) return []; const lookup = new Map(manifest.nodes.map((node) => [node.id, node])); const childIds = (node: TreeNode) => [...node.children].sort((a, b) => { const aNode = lookup.get(a)!; const bNode = lookup.get(b)!; if ((aNode.status === 'reversed') !== (bNode.status === 'reversed')) return aNode.status === 'reversed' ? 1 : -1; return Number(a.slice(1)) - Number(b.slice(1)) }); const auto = new Map<string, { x: number; y: number }>(); let leaf = 0
    const place = (id: string, column: number): number => { const item = lookup.get(id)!; const children = childIds(item); const childYs = children.map((child) => place(child, column + 1)); const y = childYs.length ? childYs.reduce((sum, value) => sum + value, 0) / childYs.length : leaf++ * 220; auto.set(id, { x: column * 330, y }); return y }
    const subtreeRoot = focusedId || manifest.root.node_id; place(subtreeRoot, 0)
    const visible = new Set<string>(); const addDescendants = (id: string) => { visible.add(id); childIds(lookup.get(id)!).forEach(addDescendants) }; addDescendants(subtreeRoot)
    return manifest.nodes.filter((item) => visible.has(item.id)).map((item) => ({ id: item.id, type: 'life', position: positions[item.id] || auto.get(item.id)!, className: `tree-node-current ${keyboardNodeId === item.id ? 'keyboard-current' : ''}`, data: { item, anchor: manifest.root.time_anchor, onInspect: selectNode, onKeyboardFocus: setKeyboardNodeId, onContinue: (nodeId: string) => { let target = lookup.get(nodeId); while (target?.status === 'reversed' && target.parent) target = lookup.get(target.parent); if (target) setFocusedId(target.id) }, onRestore: (nodeId: string) => { setFocusedId(nodeId); setSelectedDetail(null); mutate(`/sessions/${manifest.session_id}/nodes/${nodeId}/restore`) }, onGenerate: (nodeId: string, one = false) => mutate(`/sessions/${manifest.session_id}/branches/${nodeId}/generate`, { count: one ? 1 : 3 }), onManual: (nodeId: string, title: string) => mutate(`/sessions/${manifest.session_id}/branches/${nodeId}/manual-difficulty`, { title }), onRespond: (nodeId: string, text: string) => mutate(`/sessions/${manifest.session_id}/difficulties/${nodeId}/response`, { text }), onGenerateResponse: (nodeId: string) => mutate(`/sessions/${manifest.session_id}/difficulties/${nodeId}/generate-response`), onGenerateSituation: (nodeId: string) => mutate(`/sessions/${manifest.session_id}/responses/${nodeId}/generate-situation`), onManualSituation: (nodeId: string, title: string) => mutate(`/sessions/${manifest.session_id}/responses/${nodeId}/manual-situation`, { title }), onOutcome: (nodeId: string) => mutate(`/sessions/${manifest.session_id}/situations/${nodeId}/activate`), onReverse: (nodeId: string) => { setFocusedId(nodeId); setSelectedDetail(null); mutate(`/sessions/${manifest.session_id}/nodes/${nodeId}/reverse`) } } }))
  }, [manifest, focusedId, keyboardNodeId, positions])
  const canvasNodes = useMemo(() => { if (!draft) return nodes; const anchor = nodes.find((node) => node.id === draft.anchorId); if (!anchor) return nodes; return [...nodes, { id: 'draft-input', type: 'draft', position: { x: anchor.position.x + (draft.relation === 'child' ? 330 : 0), y: anchor.position.y + 180 }, data: { type: draft.type, onSubmit: submitDraft, onCancel: () => setDraft(null) }, draggable: false, selectable: false } as Node] }, [nodes, draft])
  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.target instanceof HTMLInputElement || event.target instanceof HTMLTextAreaElement || event.target instanceof HTMLButtonElement || (event.target instanceof HTMLElement && event.target.isContentEditable) || nodes.length === 0) return
      const current = nodes.find((node) => node.id === keyboardNodeId) || nodes[0]
      const moveTo = (next: typeof nodes[number] | undefined) => { if (!next) return; event.preventDefault(); setKeyboardNodeId(next.id); document.querySelector<HTMLElement>(`.react-flow__node[data-id="${next.id}"] .life-node`)?.focus(); flow?.setCenter(next.position.x + 126, next.position.y + 60, { zoom: 0.92, duration: 180 }) }
      const createDraft = (relation: Draft['relation']) => { const item = current.data.item; const childTypes: Partial<Record<TreeNode['type'], Draft['type']>> = { decision: 'branch', branch: 'difficulty', difficulty: 'response', response: 'situation' }; const siblingTypes: Partial<Record<TreeNode['type'], Draft['type']>> = { branch: 'branch', difficulty: 'difficulty', response: 'response', situation: 'situation' }; const type = relation === 'child' ? childTypes[item.type] : siblingTypes[item.type]; const parentId = relation === 'child' ? item.id : item.parent; if (!type || !parentId) return; event.preventDefault(); setDraft({ parentId, type, relation, anchorId: item.id }) }
      if (event.key === 'Tab') { createDraft('child'); return }
      if (event.key === 'Enter') { createDraft('sibling'); return }
      if (event.key === ' ') { event.preventDefault(); if (current.data.item.status === 'active') { setFocusedId(current.id); setSelectedDetail(null) } return }
      if (event.key === 'Escape') { event.preventDefault(); if (selectedDetail) setSelectedDetail(null); else setFocusedId(null); return }
      const direction = event.key.replace('Arrow', '').toLowerCase()
      if (!['left', 'right', 'up', 'down'].includes(direction)) return
      const candidates = nodes.filter((node) => node.id !== current.id).filter((node) => direction === 'left' ? node.position.x < current.position.x : direction === 'right' ? node.position.x > current.position.x : direction === 'up' ? node.position.y < current.position.y : node.position.y > current.position.y)
      const next = candidates.sort((a, b) => { const score = (node: typeof nodes[number]) => { const dx = Math.abs(node.position.x - current.position.x); const dy = Math.abs(node.position.y - current.position.y); return (direction === 'left' || direction === 'right') ? dx * 4 + dy : dy * 4 + dx }; return score(a) - score(b) })[0]
      moveTo(next)
    }
    window.addEventListener('keydown', onKeyDown); return () => window.removeEventListener('keydown', onKeyDown)
  }, [nodes, keyboardNodeId, flow, selectedDetail])
  const edges = useMemo(() => { const visibleIds = new Set(nodes.map((node) => node.id)); return manifest?.nodes.filter((node) => node.parent && visibleIds.has(node.parent) && visibleIds.has(node.id)).map((node) => ({ id: `${node.parent}-${node.id}`, source: node.parent!, target: node.id, animated: node.status === 'pending', className: node.status === 'reversed' ? 'retired-edge' : '' })) || [] }, [manifest, nodes])
  const pendingCount = manifest?.nodes.filter((node) => node.status === 'pending').length || 0
  const focusedNode = focusedId ? manifest?.nodes.find((node) => node.id === focusedId) : null
  const breadcrumbs = useMemo(() => { if (!focusedNode || !manifest) return []; const lookup = new Map(manifest.nodes.map((node) => [node.id, node])); const path: TreeNode[] = []; let current: TreeNode | undefined = focusedNode; while (current) { path.unshift(current); current = current.parent ? lookup.get(current.parent) : undefined } return path }, [focusedNode, manifest])
  useEffect(() => { if (!flow || !manifest) return; const frame = requestAnimationFrame(() => { if (!focusedId) { flow.fitView({ padding: 0.22, maxZoom: 0.9, duration: 260 }); return } const current = nodes.find((node) => node.id === focusedId); if (current) flow.setCenter(current.position.x + 140, current.position.y + 70, { zoom: 0.92, duration: 280 }) }); return () => cancelAnimationFrame(frame) }, [flow, focusedId, manifest?.session_id])
  useEffect(() => { const header = document.querySelector<HTMLElement>('.app-shell:not(.has-session) .history-head'); const toggle = () => document.body.classList.toggle('show-all-history'); header?.addEventListener('click', toggle); return () => header?.removeEventListener('click', toggle) }, [manifest])
  return <main className={`app-shell ${manifest ? 'has-session' : ''} ${selectedDetail ? 'with-detail' : ''}`}>
    <aside><div className="brand"><Sparkles size={20} />人生逆转模拟器</div><p>把此刻的选择，推演成可以回看的多条人生线。</p><div className="question-box"><textarea value={question} onChange={(e) => setQuestion(e.target.value)} placeholder="输入你正在面对的关键抉择" /><button onClick={() => create()} disabled={loading}>{loading ? <><LoaderCircle className="spin" size={16} />正在开始</> : <>开始推演 <Send size={16} /></>}</button></div><div className="template-label">从一个典型选择开始</div>{templates.map((item) => <button className="template" key={item} onClick={() => create(item)}>{item}</button>)}<div className="history-head"><History size={14} />最近的推演</div><div className="history-list">{history.map((session) => <button key={session.session_id} className={`history-item ${manifest?.session_id === session.session_id ? 'selected' : ''}`} onClick={() => { setFocusedId(null); setSelectedDetail(null); setPositions({}); refresh(session.session_id) }}><b>{session.title}</b><span>{new Date(session.created_at).toLocaleDateString('zh-CN')} · {session.node_count} 个节点</span>{session.pending_count > 0 && <i>推演中</i>}</button>)}{history.length === 0 && <span className="history-empty">尚无可恢复的推演</span>}</div><div className="legend"><span className="decision-dot" />抉择 <span className="difficulty-dot" />困难 <span className="situation-dot" />局面</div></aside>
    <section className="canvas"><header><div>{manifest ? <><span className="eyebrow">{focusedNode ? 'CURRENT STEP' : 'SESSION'}</span><b>{focusedNode ? `第 ${Number(focusedNode.id.slice(1))} 步 · ${focusedNode.title}` : manifest.session_id}</b></> : <><span className="eyebrow">WHAT IF</span><b>从一个选择开始</b></>}</div><div className="header-status">{focusedNode && <button className="focus-clear" onClick={() => setFocusedId(null)}><X size={13} />查看全局</button>}{pendingCount > 0 && <span className="progress-pill"><LoaderCircle size={14} />正在推演 {pendingCount} 个节点</span>}{manifest && <span className="anchor">时间锚点 {manifest.root.time_anchor}</span>}</div></header>{focusedNode && <nav className="focus-note" aria-label="当前路径"><button className="focus-parent" disabled={!focusedNode.parent} onClick={() => focusedNode.parent && setFocusedId(focusedNode.parent)}><Undo2 size={14} />返回上一级</button>{breadcrumbs.map((node, index) => <span className="crumb" key={node.id}>{index > 0 && <ChevronRight size={13} />}<button className={node.id === focusedNode.id ? 'crumb-current' : ''} onClick={() => setFocusedId(node.id)}>第 {Number(node.id.slice(1))} 步 · {node.title}</button></span>)}</nav>}{error && <div className="error">{error}</div>}{manifest ? <ReactFlow nodes={canvasNodes} edges={edges} nodeTypes={{ life: SimulatorNode, draft: DraftNode }} minZoom={0.35} maxZoom={1.5} onInit={setFlow} onNodeClick={(_, node) => node.type !== 'draft' && void selectNode(node.id)} onNodeDragStop={(_, node) => setPositions((current) => ({ ...current, [node.id]: node.position }))}><Background gap={24} size={1} /><Controls /></ReactFlow> : <div className="empty"><div><Sparkles size={32} /><h1>你会如何选择？</h1><p>每一次探索都会成为一条可回看的记忆。</p></div></div>}</section>
    {manifest && <CanvasMenu manifest={manifest} onNew={() => { updateSessionUrl(null); setManifest(null); setFocusedId(null); setSelectedDetail(null); setPositions({}) }} onReturn={() => { updateSessionUrl(null); setManifest(null); setFocusedId(null); setSelectedDetail(null); setPositions({}) }} />}
    <DetailPanel detail={selectedDetail} onClose={() => setSelectedDetail(null)} onEnter={() => { if (selectedDetail) { setFocusedId(selectedDetail.id); setSelectedDetail(null) } }} />
  </main>
}
