import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import '@xyflow/react/dist/style.css'
import './styles.css'
import './motion.css'
import './canvas.css'
import './response.css'
import './focus.css'
import './detail.css'
import './detail-layout.css'
import './workspace.css'
import './session-nav.css'
import './start-redesign.css'
import './start-grid.css'
import './start-compact.css'
import './history-more.css'
import './start-action.css'
import './inspect.css'
import './detail-visibility.css'
import './focus-layout.css'
import './sibling-actions.css'
import './sibling-interaction.css'
import App from './App'

createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>)
